In [1]:
import numpy as np
x=np.array([3,4,5])
y=np.array(x^2)
print(y)

[1 6 7]


In [2]:
import numpy as np
x=np.array([3,4,5])
y=np.array([x^2])
print(y)

[[1 6 7]]


In [3]:
import numpy as np
x=np.array([1,2,3])
y=np.array(x^2)
print(y)

[3 0 1]


In [1]:
list =[]
print(list)

[]


In [2]:
l1 = [1,2,3,"sri"]

NameError: name 'sri' is not defined

In [3]:
print(l1)

NameError: name 'l1' is not defined

In [4]:
list1=[1,2,3,"sri"]

In [5]:
print(list1)

[1, 2, 3, 'sri']


In [7]:
list=[1,2,3,4,5,"sri","papa","satya"]
list.append(6)
print(list)

[1, 2, 3, 4, 5, 'sri', 'papa', 'satya', 6]


In [12]:
for i in range[7, 16]
   list.append(i)
print(list)

SyntaxError: invalid syntax (607329724.py, line 1)

In [11]:
for i in range(1, 4)

SyntaxError: invalid syntax (37467908.py, line 1)

In [19]:
for i in range(1 , 9)
print(i)

SyntaxError: invalid syntax (3948009335.py, line 1)

In [21]:
myList=[1,2,3,"sri"] 
myList.append(4)
myList.append(5)
myList.append(6)
for i in range(7, 9):
    myList.append(i)
print(myList)

[1, 2, 3, 'sri', 4, 5, 6, 7, 8]


In [24]:
lakshmisri=[1,2,3,4,5,"sri"]
lakshmisri.append(8)
for i in range(11, 15):
    lakshmisri.append(i)
print(lakshmisri)

[1, 2, 3, 4, 5, 'sri', 8, 11, 12, 13, 14]


In [25]:
lakshmisri.extend([4,5,6])
print(lakshmisri)

[1, 2, 3, 4, 5, 'sri', 8, 11, 12, 13, 14, 4, 5, 6]


In [28]:
bhumi=[12,13,6,"prudvi"]
bhumi.extend([7,8,9])
for i in range(9,15):
    bhumi.append(i)
print(bhumi)

[12, 13, 6, 'prudvi', 7, 8, 9, 9, 10, 11, 12, 13, 14]


In [30]:
geetha=[4,5,6,7,8]
geetha.insert(2,9)
print(geetha)

[4, 5, 9, 6, 7, 8]


###### 

In [35]:
r=["sri","priya"]
r.insert(9,"srilu")
print(r)

['sri', 'priya', 'srilu']


In [4]:
s=["sri",1,3,4,1,2,3,"priya","sri","lakshmisri"]
s.remove("sri")
print(s)

[1, 3, 4, 1, 2, 3, 'priya', 'sri', 'lakshmisri']


In [7]:
s.remove(3)
print(s)

[1, 4, 1, 2, 'priya', 'sri', 'lakshmisri']


In [8]:
s.pop(3)

2

In [9]:
print(s)

[1, 4, 1, 'priya', 'sri', 'lakshmisri']


In [15]:
sri=["geetha","mouni","rupiii","anitha",23,3,4,54,65,65]
print(sri[3:])

['anitha', 23, 3, 4, 54, 65, 65]


In [12]:
print(sri[:11])

['geetha', 'mouni', 'rupiii', 'anitha', 23, 3, 4, 54, 65, 65]


In [14]:
print(sri[2:4])

['rupiii', 'anitha']


In [17]:
print(sri[::-1])

[65, 65, 54, 4, 3, 23, 'anitha', 'rupiii', 'mouni', 'geetha']


In [20]:
sri.reverse(-2)
print(len(sri))

TypeError: list.reverse() takes no arguments (1 given)

In [21]:
print(len(sri))

10


In [28]:
me=["priya","sri","azzzzz","zip","x"]
print(max(me))

zip


In [31]:
me.count(('azzzzz'))

1

In [4]:
lakshmi=[1,2,3,4,5,"bhumi",7]
sri=["sorry",23,2,45,65,43,78]
lakshmisri=lakshmi+sri
print(lakshmisri)

[1, 2, 3, 4, 5, 'bhumi', 7, 'sorry', 23, 2, 45, 65, 43, 78]


In [6]:
list=[1,2,3]
print(list*2)

[1, 2, 3, 1, 2, 3]


In [7]:
print(sri.index(43))

5


In [8]:
oye=[1,2,3,4,"sri","surya"]
oye.clear()

In [9]:
print(oye)

[]
